name: Build Desktop (macOS & Windows & Linux)

on:
    push:
        branches: [main, master]
    workflow_dispatch:

env:
    FLUTTER_CHANNEL: stable

jobs:
    build-macos:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4

            - name: Cache pub
              uses: actions/cache@v4
              with:
                  path: ~/.pub-cache
                  key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
                  restore-keys: ${{ runner.os }}-pub-

            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: ${{ env.FLUTTER_CHANNEL }}

            - name: Resolve deps & enable macOS
              run: |
                  flutter --version
                  flutter config --enable-macos-desktop
                  flutter pub get

            - name: Build macOS (release)
              run: flutter build macos --release

            - name: Zip .app
              run: |
                  cd build/macos/Build/Products/Release
                  ditto -c -k --sequesterRsrc --keepParent *.app macos-app.zip

            - name: Upload macOS artifact
              uses: actions/upload-artifact@v4
              with:
                  name: macos-app
                  path: build/macos/Build/Products/Release/macos-app.zip

    build-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4

            - name: Cache pub
              uses: actions/cache@v4
              with:
                  path: ~/.pub-cache
                  key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
                  restore-keys: ${{ runner.os }}-pub-

            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: ${{ env.FLUTTER_CHANNEL }}

            - name: Resolve deps & enable Windows
              run: |
                  flutter --version
                  flutter config --enable-windows-desktop
                  flutter pub get

            - name: Build Windows (release)
              run: flutter build windows --release

            - name: Upload Windows artifact
              uses: actions/upload-artifact@v4
              with:
                  name: windows-app
                  path: build/windows/x64/runner/Release/**

    build-linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install deps (Linux desktop + SQLite)
              run: |
                  sudo apt-get update
                  sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libsqlite3-dev

            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: ${{ env.FLUTTER_CHANNEL }}

            - name: Build Linux
              run: |
                  flutter config --enable-linux-desktop
                  flutter pub get
                  flutter build linux --release

            - name: Pack bundle
              run: |
                  cd build/linux/x64/release
                  tar -czf meu_app_tarefas_linux_x64.tar.gz bundle

            - name: Upload Linux artifact
              uses: actions/upload-artifact@v4
              with:
                  name: linux-app
                  path: build/linux/x64/release/meu_app_tarefas_linux_x64.tar.gz
